# Generated by Django 3.2.6 on 2022-08-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('Date', models.CharField(max_length=30)),
                ('Month', models.CharField(max_length=30)),
                ('IPAddress', models.CharField(max_length=30)),
            ],
        ),
    ]
